[tag]
files = [
    { path = "src/pytoil/__init__.py", search = '__version__ = "{{.Current}}"', replace = '__version__ = "{{.Next}}"' },
    { path = "pyproject.toml", search = 'version = "{{.Current}}"', replace = 'version = "{{.Next}}"' },
]
